// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wms.Infrastructure.Persistence;

#nullable disable

namespace Wms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260323185733_AddCustomerContactMarker")]
    partial class AddCustomerContactMarker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Wms.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.HasKey("CustomerId");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.CustomerOrder", b =>
                {
                    b.Property<Guid>("CustomerOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("CustomerOrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_orders", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.CustomerOrderLine", b =>
                {
                    b.Property<Guid>("CustomerOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_order_line_id");

                    b.Property<Guid>("CustomerOrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("customer_order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("CustomerOrderLineId");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("customer_order_lines", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("transaction_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reference_id");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int")
                        .HasColumnName("reference_type");

                    b.Property<Guid?>("ReversalOfTransactionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reversal_of_transaction_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("TransactionId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ReversalOfTransactionId");

                    b.ToTable("financial_transactions", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Property<Guid>("GoodsReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("goods_receipt_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("purchase_order_id");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("received_at");

                    b.HasKey("GoodsReceiptId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("goods_receipts", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.Property<Guid>("GoodsReceiptLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("goods_receipt_line_id");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("char(36)")
                        .HasColumnName("goods_receipt_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("int")
                        .HasColumnName("quantity_received");

                    b.HasKey("GoodsReceiptLineId");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("ProductId");

                    b.ToTable("goods_receipt_lines", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int")
                        .HasColumnName("quantity_on_hand");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int")
                        .HasColumnName("reorder_threshold");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sku");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("supplier_id");

                    b.HasKey("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("purchase_order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("char(36)")
                        .HasColumnName("supplier_id");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("SupplierId");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("PurchaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("purchase_order_line_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("char(36)")
                        .HasColumnName("purchase_order_id");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int")
                        .HasColumnName("quantity_ordered");

                    b.HasKey("PurchaseOrderLineId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("purchase_order_lines", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.ReportExport", b =>
                {
                    b.Property<Guid>("ReportExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("report_export_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("file_path");

                    b.Property<int>("Format")
                        .HasColumnType("int")
                        .HasColumnName("format");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("generated_at");

                    b.Property<int>("ReportType")
                        .HasColumnType("int")
                        .HasColumnName("report_type");

                    b.HasKey("ReportExportId");

                    b.ToTable("report_exports", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("stock_movement_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("reference_id");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int")
                        .HasColumnName("reference_type");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("StockMovementId");

                    b.HasIndex("ProductId", "OccurredAt");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.HasKey("SupplierId");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Customer", b =>
                {
                    b.OwnsOne("Wms.Domain.ValueObjects.ContactDetails", "Contact", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Address")
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("address");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("varchar(320)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(32)
                                .HasColumnType("varchar(32)")
                                .HasColumnName("phone");

                            b1.Property<bool>("contact_marker")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("contact_marker");

                            b1.HasKey("CustomerId");

                            b1.ToTable("customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Wms.Domain.Entities.CustomerOrder", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.CustomerOrderLine", b =>
                {
                    b.HasOne("Wms.Domain.Entities.CustomerOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wms.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Wms.Domain.ValueObjects.Money", "UnitPriceAtSale", b1 =>
                        {
                            b1.Property<Guid>("CustomerOrderLineId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("GBP")
                                .HasColumnName("unit_price_currency");

                            b1.HasKey("CustomerOrderLineId");

                            b1.ToTable("customer_order_lines");

                            b1.WithOwner()
                                .HasForeignKey("CustomerOrderLineId");
                        });

                    b.Navigation("UnitPriceAtSale")
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("Wms.Domain.Entities.FinancialTransaction", null)
                        .WithMany()
                        .HasForeignKey("ReversalOfTransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Wms.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FinancialTransactionTransactionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("GBP")
                                .HasColumnName("currency");

                            b1.HasKey("FinancialTransactionTransactionId");

                            b1.ToTable("financial_transactions");

                            b1.WithOwner()
                                .HasForeignKey("FinancialTransactionTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("Wms.Domain.Entities.PurchaseOrder", null)
                        .WithMany("Receipts")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.HasOne("Wms.Domain.Entities.GoodsReceipt", null)
                        .WithMany("Lines")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wms.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.Product", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Wms.Domain.ValueObjects.Money", "UnitCost", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("unit_cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("GBP")
                                .HasColumnName("unit_cost_currency");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("UnitCost")
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wms.Domain.Entities.PurchaseOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wms.Domain.ValueObjects.Money", "UnitCostAtOrder", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderLineId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("unit_cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(3)
                                .HasColumnType("varchar(3)")
                                .HasDefaultValue("GBP")
                                .HasColumnName("unit_cost_currency");

                            b1.HasKey("PurchaseOrderLineId");

                            b1.ToTable("purchase_order_lines");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderLineId");
                        });

                    b.Navigation("UnitCostAtOrder")
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.ReportExport", b =>
                {
                    b.OwnsOne("Wms.Domain.ValueObjects.DateRange", "DateRange", b1 =>
                        {
                            b1.Property<Guid>("ReportExportId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("From")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("range_from");

                            b1.Property<DateTime>("To")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("range_to");

                            b1.HasKey("ReportExportId");

                            b1.ToTable("report_exports");

                            b1.WithOwner()
                                .HasForeignKey("ReportExportId");
                        });

                    b.Navigation("DateRange");
                });

            modelBuilder.Entity("Wms.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.Supplier", b =>
                {
                    b.OwnsOne("Wms.Domain.ValueObjects.ContactDetails", "Contact", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Address")
                                .HasMaxLength(512)
                                .HasColumnType("varchar(512)")
                                .HasColumnName("address");

                            b1.Property<string>("Email")
                                .HasMaxLength(320)
                                .HasColumnType("varchar(320)")
                                .HasColumnName("email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(32)
                                .HasColumnType("varchar(32)")
                                .HasColumnName("phone");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Wms.Domain.Entities.CustomerOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Wms.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Receipts");
                });
#pragma warning restore 612, 618
        }
    }
}
