sonar.projectKey=alexelw_COM5043_Warehouse-Management-system
sonar.organization=alexelw
sonar.host.url=https://sonarcloud.io

# Monorepo: scan both backend and frontend source folders
sonar.sources=WMS-API/src,WMS-Frontend/src

# Exclusions for generated/build artifacts
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/dist/**,**/coverage/**

# Angular/Karma lcov output path
sonar.javascript.lcov.reportPaths=WMS-Frontend/coverage/wms-frontend/lcov.info
